### ISSUE TITLE
Selective Merge

### ISSUE THREAD

**Issue by simongeilfus** [chaoticbob/Cinder#1]
Hey Hai, 
As discussed here's a list of things I'd love to see merged in the android branch, more or less in the order of importance. Obviously the first one would be the heaviest I guess. As there was quite a big organisational change (umbrella headers), I think there's not much choices but update the whole folder at once.

- [ ] cinder/gl/*
- [ ] cinder/GeomIo.h
- [ ] cinder/ConcurrentCircularBuffer.h
- [ ] cinder/Camera.h
- [ ] cinder/CameraUi.h
- [ ] cinder/TriMesh.h

Thanks a lot! Let me know if there's an issue with any of those.

**Comment by chaoticbob** [comment]
Covered by merging with latest master.
