### ISSUE TITLE
setFullscreen

### ISSUE THREAD

**Issue by simongeilfus** [chaoticbob/Cinder#10]
Could setFullscreen be bound to setSystemUiVisibility() and its "Immersive" flags?

https://developer.android.com/training/system-ui/immersive.html

Would that be the right and easy way to get a proper equivalent to fullscreen?

**Comment by chaoticbob** [comment]
Totally possible. I honestly haven't thought really deep about this...mostly because you can do this from both the manifest and programatically. It may make more sense in the short term to do this via the manifest and the in the long term do programmatically.

**Comment by simongeilfus** [comment]
So there's a way to do this in the manifest?
The only thing I managed to do is hiding the status bar, this is what each "fullscreen" themes do. I'm afraid that removing the action bar on the other hand needs some java code. Maybe I'm wrong, but that's what I've understood by reading the docs and a few stackoverflow.

**Comment by chaoticbob** [comment]
Implemented. After some research...there wasn't a way to do it from the manifest.

```cpp
void prepareSettings( Sensors::Settings* settings )
{
	settings->setFullScreen( true );
}
...
// This line tells Cinder to actually create the application
CINDER_APP( Sensors, RendererGl, prepareSettings )
````
