### ISSUE TITLE
Fix to getMousePos() breaks multitouch behavior.

### ISSUE THREAD

**Issue by sansumbrella** [chaoticbob/Cinder#11]
At 985ad5f, multitouch was enabled by default and works as expected. At 176739c, multitouch events are no longer called by default. The previous behavior matches that of Cinder on iOS.

Will try adjusting the application settings passed to the macro to see if they provide expected behavior.

**Comment by sansumbrella** [comment]
Confirmed. Setting `setMultiTouchEnabled` at startup restores expected behavior. It should be enabled by default on mobile.

**Comment by chaoticbob** [comment]
Cool - will swap this around.

**Comment by chaoticbob** [comment]
Done.
