### ISSUE TITLE
Camera Texture sampling in ES2 shaders

### ISSUE THREAD

**Issue by sansumbrella** [chaoticbob/Cinder#15]
I'm trying to use ES2 shaders to render the hardware camera texture on Android. I noticed that the NormalMappingBasic sample uses ES2, so I am surprised that my own ES2 shaders don't produce output on Android.

On iOS, the result is as expected (a blurred version of the input texture):
![img_1072](https://cloud.githubusercontent.com/assets/81553/7947228/c09551ec-0949-11e5-94a0-b27a7982c172.PNG)

On Android, I only see a black screen. If I instead output the texture coordinates as colors, I see the expected gradient of color.

Is there some secret to textures being bound on Android that is different from other platforms?

(The white dot is drawn later)

**Comment by sansumbrella** [comment]
Shader code for reference:

vs:
```glsl
#version 100

precision highp float;

attribute vec4  ciPosition;
attribute vec2  ciTexCoord0;

varying vec2 vTexCoord;

void main()
{
  gl_Position = ciPosition; // we specify position in NDC
  vTexCoord = ciTexCoord0; // offsetTextureCoordinate( ciTexCoord0, uFrameIndex );
}
```

fs:
```glsl
#version 100

precision highp float;

// Size of a single texel in an input camera image.
const vec2 texelSize = vec2( 1.0 ) / vec2( 640, 480 );

uniform sampler2D	uSampler;

varying vec2 vTexCoord;

void main( void )
{
	vec4 sum = vec4( 0.0 );
	sum += texture2D( uSampler, vTexCoord + -10.0 * texelSize ) * 0.009167927656011385;
	sum += texture2D( uSampler, vTexCoord +  -9.0 * texelSize ) * 0.014053461291849008;
	sum += texture2D( uSampler, vTexCoord +  -8.0 * texelSize ) * 0.020595286319257878;
	sum += texture2D( uSampler, vTexCoord +  -7.0 * texelSize ) * 0.028855245532226279;
	sum += texture2D( uSampler, vTexCoord +  -6.0 * texelSize ) * 0.038650411513543079;
	sum += texture2D( uSampler, vTexCoord +  -5.0 * texelSize ) * 0.049494378859311142;
	sum += texture2D( uSampler, vTexCoord +  -4.0 * texelSize ) * 0.060594058578763078;
	sum += texture2D( uSampler, vTexCoord +  -3.0 * texelSize ) * 0.070921288047096992;
	sum += texture2D( uSampler, vTexCoord +  -2.0 * texelSize ) * 0.079358891804948081;
	sum += texture2D( uSampler, vTexCoord +  -1.0 * texelSize ) * 0.084895951965930902;
	sum += texture2D( uSampler, vTexCoord +   0.0 * texelSize ) * 0.086826196862124602;
	sum += texture2D( uSampler, vTexCoord +   1.0 * texelSize ) * 0.084895951965930902;
	sum += texture2D( uSampler, vTexCoord +   2.0 * texelSize ) * 0.079358891804948081;
	sum += texture2D( uSampler, vTexCoord +   3.0 * texelSize ) * 0.070921288047096992;
	sum += texture2D( uSampler, vTexCoord +   4.0 * texelSize ) * 0.060594058578763078;
	sum += texture2D( uSampler, vTexCoord +   5.0 * texelSize ) * 0.049494378859311142;
	sum += texture2D( uSampler, vTexCoord +   6.0 * texelSize ) * 0.038650411513543079;
	sum += texture2D( uSampler, vTexCoord +   7.0 * texelSize ) * 0.028855245532226279;
	sum += texture2D( uSampler, vTexCoord +   8.0 * texelSize ) * 0.020595286319257878;
	sum += texture2D( uSampler, vTexCoord +   9.0 * texelSize ) * 0.014053461291849008;
	sum += texture2D( uSampler, vTexCoord +  10.0 * texelSize ) * 0.009167927656011385;

	gl_FragColor = sum;
//  gl_FragColor = vec4( vTexCoord, 0.5, 1.0 );
}
```

**Comment by sansumbrella** [comment]
The good news is it looks like there is a `GL_INVALID_ENUM` error somewhere in the code. Maybe something wrong with the texture binding?

**Comment by sansumbrella** [comment]
The `GL_INVALID_ENUM` is happening at the point when I copy the capture texture to my own texture:

```c++
mTexture = mCapture->getTexture();
```

Any ideas why that might be the case? Also, if we updated to the latest Cinder/glNext, I could update my texture with the camera surface, which may circumvent that issue.

**Comment by sansumbrella** [comment]
Making things extra mysterious is the fact that `gl::draw( mTexture );` still works despite the initial invalid enum. And I don't _think_ it does anything special with the sampling.

**Comment by sansumbrella** [comment]
Okay, looks like the camera uses a `samplerExternalOES`, which needs to be enabled in the shader with `#extension GL_OES_EGL_image_external : require`.

**Comment by sansumbrella** [comment]
I would prefer the ability to get the capture's surface and put it into a texture with the format of my choosing. It's tricky to write custom shaders not knowing the incoming texture format.

**Comment by chaoticbob** [comment]
I'll change getTexture to getTextureAndroid...and make getTexture behave like the other platforms. Just keep in mind that there will be performance penalty because the app will now incur the cost of decoding the NV21 or YUV420 data on the CPU. 

Just for performance considerations - is there you can a way you slap a #define ANDROID before creating GlslProg from source? And then do an #ifdef inside your shader for the sampler? I think the rest of the code should remain the same. I know it's a bit weird in the routing...but if you have a large image size from the camera - it may save some CPU cycles.

**Comment by sansumbrella** [comment]
At least as of recently, Capture doesn't provide a `getTexture` method on iOS at all. Now that I know it's coming in a different format, I can easily work around it if I create my own texture from the surface. Naming the function `getTextureAndroid` might help clarify that something special is happening, though.

**Comment by chaoticbob** [comment]
You're right...most other platforms don't have a direct to texture capture yet. I'll get this sorted later today and write up some small notes should you want to optimize the NV21/YUV420 decode.

**Comment by sansumbrella** [comment]
Also, thanks for explaining the value of the OES textures.

**Comment by chaoticbob** [comment]
So I just checked on this...apologies on this, but I think the CaptureBasic sample obscured that getSurface was implemented and working - should decode to a working RGB Surface. I just double checked with a Nexus 5 and Nvidia shield. Let me know if this does what you need.

**Comment by chaoticbob** [comment]
Going to assume that things are working based on our conversations. Let me know if you run into anything else.
