### ISSUE TITLE
MotionManager::getRotation rotates camera around incorrect axes

### ISSUE THREAD

**Issue by sansumbrella** [chaoticbob/Cinder#18]
On iOS, `camera.setOrientation(MotionManager::getRotation());` orients the perspective camera along a view that moves predictably when the devices is rotated in space. The Android version seems to have a few axes confused; perhaps needs a correction rotation to be applied.

Will see if I can get that sorted in-app.

**Comment by sansumbrella** [comment]
Will try to upload a video of this behavior. Currently down to 22MB on the video; needs to be 10...

**Comment by sansumbrella** [comment]
Okay, github doesn't support videos, so I put one on [Dropbox](https://www.dropbox.com/s/nolklqsb0j2cfds/android_orientation_01.mov?dl=0).

**Comment by sansumbrella** [comment]
Quick sketch of what I observed for the axes:
![img_1091](https://cloud.githubusercontent.com/assets/81553/8065935/b018251a-0eb2-11e5-995f-fe84b20db4e2.JPG)


1) x-axis device motion created motion around the y-axis for the camera.
2) z-axis device motion was inverted.
3) y-axis device motion was incorrectly represented (the app stopped running for me, but it was probably causing x-axis motion).

**Comment by sansumbrella** [comment]
![img_1091](https://cloud.githubusercontent.com/assets/81553/8065970/ebfa05da-0eb2-11e5-90ce-8a076e307eb0.JPG)

**Comment by chaoticbob** [comment]
I made some updates. It's closer...buts till not exactly the same yet. I need to spend more time with the math.

**Comment by sansumbrella** [comment]
Thanks, I'll have a look.

**Comment by chaoticbob** [comment]
Made some more updates to the behavior. Using a different set of sensors that are fused.

**Comment by sansumbrella** [comment]
This is mostly correct now. I sometimes still see strange sensor values on the N5, but generally waving the device around works as expected.
