### ISSUE TITLE
Exposing Gyroscope events

### ISSUE THREAD

**Issue by simongeilfus** [chaoticbob/Cinder#2]

**Comment by simongeilfus** [comment]
There might be a small typo here:

```c++
#elif defined( CIDNER_ANDROID )
        sInst->mImpl = std::make_shared<MotionImplAndroid>();
#endif     
```

https://github.com/chaoticbob/Cinder/blob/android/blocks/MotionManager/src/cinder/MotionManager.cpp#L113

Which I could send a PR ;)

**Comment by chaoticbob** [comment]
You don't use the CIDNER framework? 

Fixed the typo.

**Comment by sansumbrella** [comment]
Looks like the gyroscope is getting close.

iOS provides a quaternion for the device "attitude". It looks like android provides a Java method for getting a quaternion from the sensor, but I'm not sure how to approach converting the acceleration into a quaternion.

**Comment by sansumbrella** [comment]
Where is the Java underlying the MotionManager for Android? Some searching suggests that `Sensor.TYPE_ROTATION_VECTOR` will provide similar information to iOS's `deviceMotion.attitude.quaternion`. I'd love to be able to plug that in to the `getRotation()` function of `MotionManager`.

**Comment by chaoticbob** [comment]
Implemented. Wrote a basic test for it. Let me know what you see.
