### ISSUE TITLE
arm64-v8a build fails due to Json::Value constructor being ambiguous

### ISSUE THREAD

**Issue by chaoticbob** [chaoticbob/Cinder#20]
src/cinder/Json.cpp:193:32: error: call of overloaded 'Value(int64_t&)' is ambiguous
init( key, Json::Value( value ), true, NODE_VALUE, VALUE_INT );

**Comment by pizthewiz** [comment]
I  think the linux fork also ran into this and was sorted in PetrosKataras/Cinder@54163a3d91b0f0d1c53e0c6cb36626fa69e9ffa2 - there is a bit of discussion on the forum in [Re: Next Steps for the Linux Fork](https://forum.libcinder.org/topic/next-steps-for-the-linux-fork#23286000002233007) and the response.

**Comment by chaoticbob** [comment]
@pizthewiz thanks for this dude. Totally fixed it!
