### ISSUE TITLE
Support shader preprocessor defines.

### ISSUE THREAD

**Issue by sansumbrella** [chaoticbob/Cinder#21]
In mainline Cinder, gl::GlslProg::Format has support for `define()`, which lets us add preprocessor macros to our GLSL programs. Would love to see that support added to this branch as well.

At present, I only need to check if I'm running Android. Is there a stopgap measure I can use in GLSL, or should I try merging the mainline code into this branch?

**Comment by chaoticbob** [comment]
Latest changes from master branch has been merged into android_master_merge now.
