### ISSUE TITLE
Callbacks/events for application entering and leaving the foreground

### ISSUE THREAD

**Issue by sansumbrella** [chaoticbob/Cinder#24]
Currently, I don't see any way to know when an application is entering or leaving the foreground/active use. In order to do things like turn off/on the camera and sensors, we need to know about the application's foreground status.

**Comment by sansumbrella** [comment]
On iOS, there are a series of signals for things like `WillEnterForeground` and `WillResumeActive`. I assume Android provides similar events, but they aren't exposed through Cinder yet.

**Comment by chaoticbob** [comment]
So what made the most sense was the gained/lost focus events that are common to all the different ways an Activity can stop/restart, foreground/background, etc.

Has been commited: https://github.com/chaoticbob/Cinder/commit/bc534e3703861edadf80af1236ce03626fde0ba3

Example:
https://github.com/chaoticbob/Cinder/blob/bc534e3703861edadf80af1236ce03626fde0ba3/test/Android/ActivityStartStop/src/ActivityStartStop.cpp#L31-L35

You need to set this in the c'tor. Setup can't be trusted to get called before the GainedFocus event to guarantee it.
