### ISSUE TITLE
Android devices go into idle mode when user doesn't touch screen

### ISSUE THREAD

**Issue by sansumbrella** [chaoticbob/Cinder#25]
Is there a way to prevent the device idling in Cinder-Android?

Whether or not fullscreen mode is enabled, the device goes to sleep unless someone touches the screen within the timeout delay.

**Comment by chaoticbob** [comment]
Yes. There's a request you can make to the OS to not have this behavior. I will add some logic to setFullscreen and a separate function call to prevent this from happening.

**Comment by chaoticbob** [comment]
Added. https://github.com/chaoticbob/Cinder/commit/39ee4fbc95430b0a286e9f69bd123a67224b3296

```C++
void prepareSettings( CaptureBasicApp::Settings* settings )
{
	settings->setKeepScreenOn( true );
}
```
