### ISSUE TITLE
JSON Status [Android]

### ISSUE THREAD

**Issue by sansumbrella** [chaoticbob/Cinder#3]
What is the status of JSON parsing on Android? I'm getting messages that look like linker errors after all my original project files compile.

Android Studio fails to create the `.so` from my sources with `undefined reference` errors wherever I am using Cinder's Json parser (seems like a linker error).
```
Error:(162) undefined reference to 'cinder::JsonTree::ParseOptions::ParseOptions()'
Error:(163) undefined reference to 'cinder::JsonTree::operator[](std::string const&)'
…
```

I can switch to using XML in the interim if that is supported.

**Comment by sansumbrella** [comment]
Update: switched to using XmlTree on Android, which compiles as expected. JsonTree was a non-starter.

**Comment by chaoticbob** [comment]
Fixed. https://github.com/chaoticbob/Cinder/commit/dcb0f5cb57e97495e5107856221adce9df6c37ea
