### ISSUE TITLE
.gitignore and android cruft

### ISSUE THREAD

**Issue by richardeakin** [chaoticbob/Cinder#36]
Two things:

1) There's a merge conflict in the .gitignore file in android branch.
2) There are currently per-sample .gitignore files - is it safe to move the ignored contents to the root .gitignore?  Currently the one I'm using for NodeBasic has the following contents (copied from BasicApp's):

```
.gradle
/local.properties
/.idea/workspace.xml
/.idea/libraries
.DS_Store
/build
```

I think all of that could go in the root .gitignore, if it isn't there already.

**Comment by chaoticbob** [comment]
Yes. Most of these are generated on first open for a project.

**Comment by richardeakin** [comment]
What generates the per-project .gitignore file? Or by 'yes' do you mean we should just remove all per project .gitignore files?

**Comment by chaoticbob** [comment]
Yes - remove all the per project .gitignores. I can't remember where those came from, it might have been a sample I cloned early on.

**Comment by richardeakin** [comment]
I don't think they are necessary - check out #43, I did a `find . -name .gitignore` and removed all of the ones in androidstudio projects in that.

**Comment by richardeakin** [comment]
Fixed in a different commit
