### ISSUE TITLE
Support Min Android API Level 22

### ISSUE THREAD

**Issue by richardeakin** [chaoticbob/Cinder#45]
I'm working on a project that is scoped to only support devices level 22 and up. My understanding is that if I set `NDK_PLATFORM` to 22 then the app will not be runnable on lower levels, which is diserable because we won't be testing on those.  However I'm seeing [here](https://github.com/chaoticbob/Cinder/blob/android/android/CMakeLists.txt#L122-L136) that there is no check for 'android-22'. Is it just a matter of adding that flag in there?

As an aside, I wonder if there is a way to make that check forward compatible, so that the cmake code doesn't need to be updated every time there is a new api level released (could move the `FATAL_ERROR` to a warning, even?)

**Comment by chaoticbob** [comment]
Where are you seeing android-22 in the NDK?

**Comment by richardeakin** [comment]
Ah, so that `NDK_PLATFORM` variable is different to sdk levels [documented here](https://developer.android.com/guide/topics/manifest/uses-sdk-element.html#ApiLevels) - yea that's not confusing at all. Okay, then I leave that at 21 and set 22 for gradle's minSdkVersion - easy enough. Thanks for the clarification.
