### ISSUE TITLE
implement PlatformAndroid::stackTrace()

### ISSUE THREAD

**Issue by richardeakin** [chaoticbob/Cinder#48]
Android doesn't support `execinfo.h`'s `backtrace()` and friends, we need something else for this platform. Currently I'm looking at the following impls to see what works reliably:

https://android.googlesource.com/platform/frameworks/base/+/gingerbread/libs/utils/CallStack.cpp
http://stackoverflow.com/a/28858941/506584

Both make use of libunwind.

**Comment by chaoticbob** [comment]
Implemented.
https://github.com/chaoticbob/Cinder/commit/d08f911bbcff2a454c5bba2ad5b5545a23e550da
