### ISSUE TITLE
 dequeueBuffer failed

### ISSUE THREAD

**Issue by simongeilfus** [chaoticbob/Cinder#5]
So I've been experiencing this a few time. It happen once in a while, for no clear reason. It's really hard to reproduce, doesn't happen consistently and most of the time when the app start. Every time re-running the app a second time makes the issue mysteriously disappear. 

I just wanted to see if you were you familiar with this or if it is something on my end or specific to my device? I've been trough a few stackoverflow threads about the same ```dequeueBuffer failed``` but it doesn't seem to apply to our case.

```
W/nvwsi﹕ dequeueBuffer failed, error -19
A/libc﹕/Frameworks/Cinder/cinder_android/src/cinder/app/android/RendererGlAndroid.cpp:197: virtual void cinder::app::RendererGlAndroid::swapBuffers() const: assertion "result" failed05-27 19:01:56.716  18948-
A/libc﹕ Fatal signal 6 (SIGABRT), code -6 in tid 18971 (Thread-10862)
```

**Comment by simongeilfus** [comment]
So I guess we can probably remove this assert here:
https://github.com/chaoticbob/Cinder/blob/android/src/cinder/app/android/RendererGlAndroid.cpp#L197
And let the buffer swap fail once in a while.

**Comment by chaoticbob** [comment]
This seems specific to Nvidia devices. I haven't seen it on other platforms yet. I'll keep an eye out.
