### ISSUE TITLE
current head does not compile for ios

### ISSUE THREAD

**Issue by neshume** [chaoticbob/Cinder#54]
platform_es2_features.h contains unknown tokens

**Comment by chaoticbob** [comment]
Sorry about this. The OpenGL stuff is in the process of being aligned for all that platforms as Android and Linux enter the fold. There's going to be a few speed bumps. Should be sorted soon.

**Comment by chaoticbob** [comment]
Compiles now for both ES2 and ES3.

**Comment by neshume** [comment]
Thx a lot. Great work. Already tracked and tried it out. 

Alex
