### ISSUE TITLE
empty App::getWindow()->getDisplay()

### ISSUE THREAD

**Issue by richardeakin** [chaoticbob/Cinder#55]
I'm seeing that `getWindow()->getDisplay()` returns an empty `shared_ptr<app::Display>` from both `App::setup()` and `update()`. Haven't investigated why but my guess is that `Display` isn't in use yet on android?

**Comment by chaoticbob** [comment]
Fixed. https://github.com/chaoticbob/Cinder/commit/1461772e93b6a0559a3af54c90fe0ad0abc62139

Returns a Display constructed using the screen size.
