### ISSUE TITLE
missing gl platform feature defines on android / es3

### ISSUE THREAD

**Issue by richardeakin** [chaoticbob/Cinder#58]
I had to add `CINDER_GL_HAS_TRANSFORM_FEEDBACK` and `CINDER_GL_HAS_UNIFORM_BLOCKS` in my local copy to get those features to build, not sure if there are others.

I'm seeing "Requested context : GLES 3.1" in logcat, though these symbols should be for 3+ I believe

**Comment by richardeakin** [comment]
And `CINDER_GL_HAS_DRAW_INSTANCED`, there are probably others these are just the ones I've run into.

**Comment by chaoticbob** [comment]
This should be fixed now.
