### ISSUE TITLE
Error logging / Seeing Debug Messages

### ISSUE THREAD

**Issue by sansumbrella** [chaoticbob/Cinder#6]
My application is crashing on launch, so I'm trying to use the CI_LOG_* macros to get some insight into where it's going wrong. Unfortunately, I can't see their output anywhere in Android studio.

I tried looking in the `event log`, `gradle console`, `console`, and `logcat` in Android studio. Is there somewhere else I should look, or is there something wrong with console(), cout, cerr, CI_LOG in the Cinder setup?

**Comment by simongeilfus** [comment]
Hey David,

Android Studio logging is a real pain! 

Your ```CI_LOG*``` should be in logcat, but you might want to check the log level and the filters (dropdown list on the right). It doesn't always work for some reason but one thing that might help is to add a filter there with your package name. 

Oh and from what I can see ```cout <<``` doesn't work here.

**Comment by sansumbrella** [comment]
Thanks for the tip. I'll spend some more time fiddling with the options on Monday. My first foray into the Android NDK stuff saw lots of seemingly arbitrary crashes on launch, so hopefully it goes better next week.

**Comment by sansumbrella** [comment]
Hm. I can see the errors when my program runs for a bit, but nothing appears in `logcat` if I have a crash on launch. Makes it tricky to see what caused the crash.

**Comment by sansumbrella** [comment]
When an application crashes on launch, no output is sent to `logcat` (it's empty even of prior runs logs), and the following is logged to `console`:
```
The session was restarted
Target device: lge-nexus_5-0934b1ef012f7596
Uploading file
	local path: /Users/davidwicks/Client/Active/soso/FrameTime/GridSpace/androidstudio/GridSpace/app/build/outputs/apk/app-debug.apk
	remote path: /data/local/tmp/com.sosolimited.gridspace.gridspace
No apk changes detected. Skipping file upload, force stopping package instead.
DEVICE SHELL COMMAND: am force-stop com.sosolimited.gridspace.gridspace
Launching application: com.sosolimited.gridspace.gridspace/com.sosolimited.gridspace.gridspace.GridSpaceActivity.
DEVICE SHELL COMMAND: am start -D -n "com.sosolimited.gridspace.gridspace/com.sosolimited.gridspace.gridspace.GridSpaceActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.sosolimited.gridspace.gridspace/.GridSpaceActivity }

Warning: debug info can be unavailable. Please close other application using ADB: Monitor, DDMS, Eclipse
Waiting for process: com.sosolimited.gridspace.gridspace
Connected to the target VM, address: 'localhost:8600', transport: 'socket'
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'
```

When the app runs, `logcat` shows my `console()` and `CI_LOG` output, and I see the following output in `console`:
```
The session was restarted
Target device: lge-nexus_5-0934b1ef012f7596
Uploading file
	local path: /Users/davidwicks/Client/Active/soso/FrameTime/GridSpace/androidstudio/GridSpace/app/build/outputs/apk/app-debug.apk
	remote path: /data/local/tmp/com.sosolimited.gridspace.gridspace
Installing com.sosolimited.gridspace.gridspace
DEVICE SHELL COMMAND: pm install -r "/data/local/tmp/com.sosolimited.gridspace.gridspace"
pkg: /data/local/tmp/com.sosolimited.gridspace.gridspace
Success


Launching application: com.sosolimited.gridspace.gridspace/com.sosolimited.gridspace.gridspace.GridSpaceActivity.
DEVICE SHELL COMMAND: am start -D -n "com.sosolimited.gridspace.gridspace/com.sosolimited.gridspace.gridspace.GridSpaceActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.sosolimited.gridspace.gridspace/.GridSpaceActivity }

Warning: debug info can be unavailable. Please close other application using ADB: Monitor, DDMS, Eclipse
Waiting for process: com.sosolimited.gridspace.gridspace
Connected to the target VM, address: 'localhost:8600', transport: 'socket'
```

**Comment by sansumbrella** [comment]
So the `Disconnect` happens whenever the application is closed, but nothing shows up in logcat that is useful.

Turning off all the filters, I was able to see the console output relating to the application. The first thing logged by a crashy launch is:
```
06-01 16:12:01.456      745-814/? I/ActivityManager﹕ Force stopping com.sosolimited.gridspace.gridspace appid=10086 user=-1: uninstall pkg
```

So, not very useful.

Any ideas how I can gain visibility into the app state so I can find the piece of my code that might be triggering Android to immediately shut the application down (before even reaching my new code, since it doesn't run any of my log statements).

**Comment by sansumbrella** [comment]
Summary:

Logging mostly works in Android Studio, but it's very finicky and not very fun. Cinder's `console()` and `CI_LOG_*` commands will show up in the `logcat` panels of Android Studio. I've had the best luck with the Android/logcat panel, but the Debug/logcat panel works, too.
