### ISSUE TITLE
BufferObj mapping seems broken in android branch

### ISSUE THREAD

**Issue by richardeakin** [chaoticbob/Cinder#60]
(Sorry for the lame bug report, on a deadline).

The height-map based terrain in our app broke after the recent gl commits, I rolled back to before cc46050f5d44f9e204f6 and it seems to be working again. I can't really distill this one as I don't have time at the moment, and it's only a guess but my hunch is that the InstancedTeapots sample doesn't work either. If it does @chaoticbob I can try to explain what we were drawing a bit better that stopped working.

**Comment by chaoticbob** [comment]
Fixed. https://github.com/chaoticbob/Cinder/commit/3562b6aae790364393194a8db22f83ec7d566a3f

Was a bug I created when updating ES.
