### ISSUE TITLE
MotionManager rotation pitch is flipped in landscape

### ISSUE THREAD

**Issue by richardeakin** [chaoticbob/Cinder#62]
Related code: https://github.com/chaoticbob/Cinder/blob/35103ccc71f0e705025d920b21cae383994e0927/blocks/MotionManager/src/cinder/MotionImplAndroid.cpp#L174-L188

**Comment by richardeakin** [comment]
@sansumbrella Hai says you have this working in landscape? Did you have to do any extra math to correct the rotations?

**Comment by sansumbrella** [comment]
I'm not sure that I do; for Selfie x Selfie we locked the device rotation to portrait mode.

**Comment by richardeakin** [comment]
This issue was moved to cinder/Cinder#1292
