### ISSUE TITLE
Capture::create crashes immediately

### ISSUE THREAD

**Issue by sansumbrella** [chaoticbob/Cinder#7]
Adding the `Capture::create` line to my app setup results in a crash on launch. No error is logged where I can see it.
```c++
try {
  auto capture = Capture::create( 640, 480 );
}
catch (ci::Exception &exc) {
  CI_LOG_E("Error creating capture: " << exc.what());
}
```

**Comment by chaoticbob** [comment]
Do you have camera permissions turned on in AndroidManifest.xml?

**Comment by sansumbrella** [comment]
I haven't changed that file; I'll check it out once I get the NDK installed on this machine (travelling this week).

**Comment by sansumbrella** [comment]
AndroidManifest.xml is the following. Still seeing the crash; will try getting the capture basic sample to run on android. Is there a sample or test that uses the hardware camera?

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.sosolimited.gridspace.gridspace" >
    <uses-feature   android:name="android.hardware.camera"
                    android:required="true" />
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name=".GridSpaceActivity"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:configChanges="orientation">
            <!-- Tell NativeActivity the name of or .so -->
            <meta-data android:name="android.app.lib_name"
                android:value="GridSpace" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
```

**Comment by chaoticbob** [comment]
CaptureBasic makes use of the camera. I will double check this sample against a few devices later today to verify and respond here. If you want to add me as a collaborator to your repo, I can do a quick run to see if it's crashing a loosely related component...like something else in JNI. 

Also, are you clicking the Play button or the Debug button when running?

**Comment by sansumbrella** [comment]
I'm clicking the Debug button when running. Sometimes I use the `control+D` shortcut.

**Comment by sansumbrella** [comment]
The CaptureBasic sample runs for me.

I'm going to try starting from scratch with my application and gradually adding back the functionality it has on iOS.

**Comment by sansumbrella** [comment]
I'll comment further on this issue if I figure out what was wrong with my prior setup. The CaptureBasic sample runs successfully (though the camera image is flipped).

**Comment by sansumbrella** [comment]
See #13 for the solution to this crashing problem.
