### ISSUE TITLE
Unable to disable -Werror=format-security in app builds

### ISSUE THREAD

**Issue by notlion** [chaoticbob/Cinder#72]
Before you ask why I want to do this.. It's not my code!

I don't see the CinderAppBuildPlugin adding this anywhere, so perhaps it's being added implicitly by ndk-build? This wouldn't be a problem except that it's added *after* the custom cFlags, so overrides any attempts to disable or demote it to a warning.

**Comment by chaoticbob** [comment]
After some digging figured this. Updated the plugin to handle this. In your build.grade for your app:
```
cinder {
    // .. stuff
    disableFormatStringChecks = true
}
```

This will generate this line in your Android.mk file:
```
LOCAL_DISABLE_FORMAT_STRING_CHECKS := true
```

...and demote the error back to warning.
