### ISSUE TITLE
Rotating the device/change of orientation will make the app crash.

### ISSUE THREAD

**Issue by simongeilfus** [chaoticbob/Cinder#8]
This happens also on a project freshly generated with the python script. 
Can anyone reproduce this?

Thanks a lot.
(If there's a way to force the app to stay in one orientation and avoid the crash that way, I don't mind for the moment)

**Comment by simongeilfus** [comment]
Here's the callstack when it's happening:

```V/threaded_app﹕ NativeWindowCreated: 0x425fd740 -- 0x42595e08
E/BufferQueueProducer﹕ [com.simongeilfus.grove2.grove2/com.simongeilfus.grove2.grove2.Grove2Activity] dequeueBuffer: BufferQueue has been abandoned
W/nvwsi﹕ dequeueBuffer failed, error -19
A/libc﹕ /Frameworks/Cinder/cinder_android/src/cinder/app/android/RendererGlAndroid.cpp:197: virtual void cinder::app::RendererGlAndroid::swapBuffers() const: assertion "result" failed
A/libc﹕ Fatal signal 6 (SIGABRT), code -6 in tid 11570 (Thread-7017)```

**Comment by simongeilfus** [comment]
Oh and forcing the activity android:screenOrientation to "landscape" makes the issue disappear, but that was expected.

**Comment by sansumbrella** [comment]
I saw this with a freshly generated project, too.

How do you force the screen orientation in an android project? Is there a checkbox somewhere like iOS/Xcode, or is it a bit of C++?

**Comment by simongeilfus** [comment]
Good, at least i'm not the only one!
A checkbox somewhere? Really? :) No you have to add it to the AndroidManifest.xml, I'm don't how you would do it from the c++ side though :
```xml
<application>
    ...
    <activity
           android:screenOrientation="landscape"
           android:configChanges="orientation|keyboardHidden" >
    </activity>
</application>
```

**Comment by sansumbrella** [comment]
Cool. Looks like I need to learn something about how that manifest file is put together, then.

**Comment by chaoticbob** [comment]
This happens because Android restarts the app when there's an config change. Screen rotation counts as one. Do you guys require screen rotation to work properly in your stuff? If you don't, this will be fixed when I make another pass through the activity event handling system. As you both figured out, you can lock screen orientation via the manifest. This is the recommended way to do it:
`
            android:screenOrientation="portrait"
            android:configChanges="orientation|screenSize">
`

**Comment by chaoticbob** [comment]
Going to close this since it seems like everyone is locking their app in to either portrait or landscape mode. Please reopen if this close is a mistake.
