### ISSUE TITLE
Error:Cannot get property 'mNdkBuildDir' on null object

### ISSUE THREAD

**Issue by simongeilfus** [chaoticbob/Cinder#9]
I'm getting this error message when trying to execute the task "assembleRelease". Any idea how CinderAppBuildPlugin could be null when trying to build for release? (It's not when building in debug mode.)

**Comment by simongeilfus** [comment]
I just did a fresh install and a fullbuild of all targets and this is still happening. Is there a change this could be an issue with the plugin itself? Am I the only one seeing this?

**Comment by sansumbrella** [comment]
I haven't tried doing a Release build yet, so I haven't run into this. Still struggling just to take baby steps each day.

**Comment by chaoticbob** [comment]
Fixed.

https://github.com/chaoticbob/Cinder/commit/41a022bae7cf16f8dfc5d7c453bbbb2131bdc79f
